export type LandingLang = 'en' | 'fi';

const en = {
  brand: 'Fintoke',
  banner: 'Websites, apps, SEO, and monthly care — one Finnish studio',
  underAttack: 'projects@fintoke.com',
  login: 'Log in',
  contactUs: 'Contact us',
  signUp: 'Log in',
  nav: [
    { href: '#product', label: 'Services' },
    { href: '#pricing', label: 'Packages' },
    { href: '#resources', label: 'Work' },
    { href: '#partners', label: 'Use cases' },
  ],
  heroBadge: 'Software studio',
  heroTitle: 'Websites, apps, and automation that run the company.',
  heroBody:
    'Fintoke is a software studio. We code sites, ship web apps, wire automation, and add AI where it actually saves work — from first brief to a product you can run.',
  getStarted: 'Get started',
  bookDemo: 'Book a call',
  productTabWhat: 'What we do',
  productTabHow: 'How we work',
  productTitle: 'One studio for the software your operations actually need.',
  productPanel: 'Web coding, internal tools, and automations — designed, built, and kept running.',
  productHeading: 'We design and code the product, then connect the work around it.',
  productBody:
    'Landing pages, client portals, CRMs, and the flows that fill them. AI is in the loop when it drafts, routes, or updates — not as a gimmick on the homepage.',
  floatChips: [
    'Web coding',
    'Web apps',
    'Automation',
    'SEO',
    'Maintenance',
    'Integrations',
    'Dashboards',
    'AI agents',
  ],
  whyBadge: 'Studio',
  whyTitle: 'Software that keeps the business moving',
  whyBody: 'Build once, automate the busywork, and keep the site and apps in shape — without a pile of disconnected vendors.',
  whyCards: [
    {
      kicker: 'Build',
      title: 'Web coding & web apps',
      body: 'Production Next.js sites, dashboards, and portals that match how your team works — not a template dump.',
    },
    {
      kicker: 'Run',
      title: 'Automation in the middle',
      body: 'Leads, mail, publishing, and ops in one workspace. Repeatable flows instead of a folder of scripts.',
    },
  ],
  resources: [
    {
      title: 'Privacy in the workspace',
      body: 'Client data stays in the project. Models you bring do not train someone else’s product.',
    },
    {
      title: 'Assets next to the code',
      body: 'Uploads, site files, and exports live with the build — no extra bucket to chase.',
    },
    {
      title: 'AI where it helps',
      body: 'Claude, ChatGPT, or your own agent inside the app, with real tools — not a chat toy.',
    },
    {
      title: 'Quiet delivery',
      body: 'We ship in slices you can review. Traffic and content can grow without a late-night scramble.',
    },
    {
      title: 'Keep it live',
      body: 'Updates, fixes, and small features after launch — the same studio that built it.',
    },
  ],
  globeBadge: 'Clients & delivery',
  globeTitle: 'Built to work with teams anywhere you sell',
  globeBody: 'English and Finnish from day one. Remote or on-site, the same studio process — brief, build, ship, maintain.',
  playKicker: 'Playground',
  playTitle: 'See the shape of a product',
  playBody: 'Sketch copy, flows, and pages here — then we build it properly in the studio.',
  playName: 'Studio playground',
  playHint: 'Draft with Fintoke, then we code it',
  playPrompt: 'A booking site for a Helsinki design studio, calm type, lots of white space',
  playTiles: [
    { title: 'Web copy', hint: 'Landing pages, emails, product text' },
    { title: 'Visuals', hint: 'Hero art, campaign stills, UI mood' },
    { title: 'Automation', hint: 'Leads, mail, and publish steps' },
    { title: 'Ops notes', hint: 'Calls and tasks into the work table' },
  ],
  casesKicker: 'Use cases',
  casesTitle: 'The same studio, different jobs',
  casesBody: 'Sites, apps, and operations — without a new vendor for every piece.',
  cases: [
    {
      title: 'Product teams',
      body: 'Ship the site and the tools around it from one brief.',
      items: ['Marketing sites and product pages', 'Internal dashboards and CRMs', 'AI copilots inside the workflow'],
    },
    {
      title: 'Growth & retail',
      body: 'Storefront, follow-up, and campaigns in one place.',
      items: ['Pages that can be updated without a ticket pile', 'Leads, mail, and SEO in the same workspace', 'Automations after checkout or a form'],
    },
    {
      title: 'Operations',
      body: 'Replace spreadsheet glue with software you can run.',
      items: ['Portals for clients and staff', 'Notes from calls into a work table', 'Maintenance so the stack stays current'],
    },
  ],
  packagesKicker: 'Packages',
  packagesTitle: 'Monthly work you can actually use',
  packagesBody: 'SEO modelling, web marketing, and ongoing changes to your sites and apps — from €129 to €379 a month.',
  packagesCta: 'Start with a message',
  packages: [
    {
      badge: 'Search',
      title: 'SEO modelling',
      summary: 'We map how you should rank, then keep the model current. Technical SEO plus a keyword and page plan — not a one-off PDF.',
      priceEur: '€129',
      priceUsd: '$149',
      period: '/ month',
      items: [
        'Keyword and topic model for your market',
        'On-page structure, titles, and internals',
        'Index, sitemap, and Core Web Vitals watch',
        'Monthly notes on what moved and what to change next',
      ],
    },
    {
      badge: 'Most chosen',
      title: 'Web marketing',
      summary: 'Campaigns and conversion work on the site you already have. Copy, landing tweaks, and a steady content rhythm.',
      priceEur: '€249',
      priceUsd: '$279',
      period: '/ month',
      featured: true,
      items: [
        'Landing and campaign pages that match the offer',
        'Email and social drafts for launches',
        'Two content or page updates included',
        'Simple funnel notes: traffic → form → follow-up',
      ],
    },
    {
      badge: 'Care',
      title: 'Support & site changes',
      summary: 'A monthly bucket for the live product: support, small features, copy and layout changes on sites and apps.',
      priceEur: '€379',
      priceUsd: '$419',
      period: '/ month',
      items: [
        'Priority support on email, weekday hours',
        'Included hours for site and app changes',
        'Backups, uptime watch, dependency patches',
        'Small SEO hygiene with every release',
      ],
    },
  ],
  contactEmail: 'projects@fintoke.com',
  contactTitle: 'Tell us what to build',
  contactBody: 'Write to Fintoke. Messages go to projects@fintoke.com — we reply with a plan, not a sales deck.',
  contactName: 'Name',
  contactEmailLabel: 'Email',
  contactMessage: 'What do you need?',
  contactSend: 'Send message',
  contactSending: 'Sending…',
  contactSent: 'Sent. We will write back to your email.',
  contactError: 'Could not send. Try again or email us directly.',
  footerTag: 'Software studio in Helsinki. Sites, apps, SEO, marketing, and care.',
  footerColServices: 'Services',
  footerColPackages: 'Packages',
  footerColContact: 'Contact',
  footerLegal: '© Fintoke. All rights reserved.',
};

const fi: typeof en = {
  brand: 'Fintoke',
  banner: 'Sivut, sovellukset, SEO ja kuukausittainen ylläpito — yksi suomalainen studio',
  underAttack: 'projects@fintoke.com',
  login: 'Kirjaudu',
  contactUs: 'Ota yhteyttä',
  signUp: 'Kirjaudu',
  nav: [
    { href: '#product', label: 'Palvelut' },
    { href: '#pricing', label: 'Paketit' },
    { href: '#resources', label: 'Työ' },
    { href: '#partners', label: 'Käyttötapaukset' },
  ],
  heroBadge: 'Ohjelmistostudio',
  heroTitle: 'Sivut, sovellukset ja automaatio, joka pyörittää yritystä.',
  heroBody:
    'Fintoke on ohjelmistostudio. Koodaamme sivut, toimitamme web-sovellukset, kytkemme automaation ja lisäämme tekoälyn sinne missä se säästää työtä — ensimmäisestä briefistä tuotteeseen, jota voi pyörittää.',
  getStarted: 'Aloita',
  bookDemo: 'Varaa palaveri',
  productTabWhat: 'Mitä teemme',
  productTabHow: 'Miten työskentelemme',
  productTitle: 'Yksi studio ohjelmistolle, jota operaatiot oikeasti tarvitsevat.',
  productPanel: 'Web-koodaus, sisäiset työkalut ja automaatiot — suunniteltu, rakennettu ja pidetty käynnissä.',
  productHeading: 'Suunnittelemme ja koodaamme tuotteen, sitten kytkemme työn sen ympärille.',
  productBody:
    'Landing-sivut, asiakasportaalit, CRM:t ja virrat, jotka täyttävät ne. Tekoäly on mukana kun se luonnostelee, ohjaa tai päivittää — ei kikkana etusivulla.',
  floatChips: [
    'Web-koodaus',
    'Web-sovellukset',
    'Automaatio',
    'SEO',
    'Ylläpito',
    'Integraatiot',
    'Dashboardit',
    'AI-agentit',
  ],
  whyBadge: 'Studio',
  whyTitle: 'Ohjelmisto, joka pitää liiketoiminnan liikkeessä',
  whyBody: 'Rakenna kerran, automatisoi rutiinit ja pidä sivut ja sovellukset kunnossa — ilman erillistä toimittajaa joka palaselle.',
  whyCards: [
    {
      kicker: 'Rakenna',
      title: 'Web-koodaus ja web-sovellukset',
      body: 'Tuotantoon Next.js-sivut, dashboardit ja portaalit, jotka vastaavat tiimin työtä — ei mallipohjakasaa.',
    },
    {
      kicker: 'Pyöritä',
      title: 'Automaatio keskellä',
      body: 'Liidit, posti, julkaisu ja operaatiot yhdessä työtilassa. Toistuvat virrat skriptikansion sijaan.',
    },
  ],
  resources: [
    {
      title: 'Tietosuoja työtilassa',
      body: 'Asiakasdata pysyy projektissa. Tuomasi mallit eivät kouluta jonkun muun tuotetta.',
    },
    {
      title: 'Aineistot koodin vieressä',
      body: 'Lataukset, sivutiedostot ja viennit elävät buildin kanssa — ei erillistä ämpäriä jahdattavaksi.',
    },
    {
      title: 'Tekoäly siellä missä auttaa',
      body: 'Claude, ChatGPT tai oma agentti sovelluksessa, oikeilla työkaluilla — ei chat-lelua.',
    },
    {
      title: 'Rauhallinen toimitus',
      body: 'Toimitamme paloissa, jotka voi tarkistaa. Liikenne ja sisältö voivat kasvaa ilman yökiirettä.',
    },
    {
      title: 'Pidä se elossa',
      body: 'Päivitykset, korjaukset ja pienet ominaisuudet julkaisun jälkeen — sama studio joka rakensi.',
    },
  ],
  globeBadge: 'Asiakkaat ja toimitus',
  globeTitle: 'Toimii tiimien kanssa siellä missä myyt',
  globeBody: 'Englanti ja suomi heti. Etänä tai paikan päällä, sama studioprosessi — brief, toteutus, julkaisu, ylläpito.',
  playKicker: 'Hiekkalaatikko',
  playTitle: 'Näe tuotteen muoto',
  playBody: 'Luonnostele tekstit, virrat ja sivut tässä — sitten rakennamme sen kunnolla studiossa.',
  playName: 'Studio-hiekkalaatikko',
  playHint: 'Luonnostele Fintokella, me koodaamme',
  playPrompt: 'Varaussivusto helsinkiläiselle designstudiolle, rauhallinen typografia, paljon tilaa',
  playTiles: [
    { title: 'Web-tekstit', hint: 'Landing-sivut, sähköpostit, tuotekopy' },
    { title: 'Visuaalit', hint: 'Hero-kuvat, kampanjat, UI-fiilis' },
    { title: 'Automaatio', hint: 'Liidit, posti ja julkaisuaskeleet' },
    { title: 'Operaatiomuistiinpanot', hint: 'Puhelut ja tehtävät työpöydälle' },
  ],
  casesKicker: 'Käyttötapaukset',
  casesTitle: 'Sama studio, eri työt',
  casesBody: 'Sivut, sovellukset ja operaatiot — ilman uutta toimittajaa joka palaselle.',
  cases: [
    {
      title: 'Tuotetiimit',
      body: 'Toimita sivusto ja sen ympärillä olevat työkalut yhdellä briefillä.',
      items: ['Markkinointisivut ja tuotesivut', 'Sisäiset dashboardit ja CRM:t', 'AI-copilotit työnkulussa'],
    },
    {
      title: 'Kasvu ja retail',
      body: 'Kauppa, follow-up ja kampanjat yhdessä paikassa.',
      items: ['Sivut, joita voi päivittää ilman tikettikasaa', 'Liidit, posti ja SEO samassa työtilassa', 'Automaatiot kassan tai lomakkeen jälkeen'],
    },
    {
      title: 'Operaatiot',
      body: 'Korvaa taulukkoliima ohjelmistolla, jota voi pyörittää.',
      items: ['Portaalit asiakkaille ja henkilöstölle', 'Puhelumuistiinpanot työpöydälle', 'Ylläpito, jotta pino pysyy ajan tasalla'],
    },
  ],
  packagesKicker: 'Paketit',
  packagesTitle: 'Kuukausityö, josta on oikeasti hyötyä',
  packagesBody: 'SEO-mallinnus, web-markkinointi ja jatkuvat muutokset sivuihin ja sovelluksiin — 129–379 € kuukaudessa.',
  packagesCta: 'Aloita viestillä',
  packages: [
    {
      badge: 'Haku',
      title: 'SEO-mallinnus',
      summary: 'Mallinnamme miten teidän pitäisi näkyä, ja pidämme mallin ajan tasalla. Tekninen SEO plus avainsana- ja sivusuunnitelma — ei kertaluontoista PDF:ää.',
      priceEur: '129 €',
      priceUsd: '$149',
      period: '/ kk',
      items: [
        'Avainsana- ja teema-malli teidän markkinaan',
        'On-page-rakenne, titlet ja sisäiset linkit',
        'Indeksi, sivukartta ja Core Web Vitals',
        'Kuukausimuistio: mikä liikkui ja mitä muutetaan',
      ],
    },
    {
      badge: 'Suosituin',
      title: 'Web-markkinointi',
      summary: 'Kampanjat ja konversio työssä olevalla sivustolla. Tekstit, landing-muutokset ja tasainen sisältötahti.',
      priceEur: '249 €',
      priceUsd: '$279',
      period: '/ kk',
      featured: true,
      items: [
        'Landing- ja kampanjasivut tarjouksen mukaan',
        'Sähköposti- ja some-luonnokset lanseerauksiin',
        'Kaksi sisältö- tai sivupäivitystä mukana',
        'Yksinkertainen funnel: liikenne → lomake → follow-up',
      ],
    },
    {
      badge: 'Ylläpito',
      title: 'Tuki ja sivumuutokset',
      summary: 'Kuukausittainen kiintiö live-tuotteelle: tuki, pienet ominaisuudet, teksti- ja layout-muutokset sivuihin ja sovelluksiin.',
      priceEur: '379 €',
      priceUsd: '$419',
      period: '/ kk',
      items: [
        'Prioriteettituki sähköpostitse, arkipäivät',
        'Tunnit sivun ja sovelluksen muutoksiin',
        'Varmuuskopiot, uptime, riippuvuuspaikkaukset',
        'Pieni SEO-huolto jokaisen julkaisun yhteydessä',
      ],
    },
  ],
  contactEmail: 'projects@fintoke.com',
  contactTitle: 'Kerro, mitä rakennetaan',
  contactBody: 'Kirjoita Fintokelle. Viestit menevät osoitteeseen projects@fintoke.com — vastaamme suunnitelmalla, emme myyntideckillä.',
  contactName: 'Nimi',
  contactEmailLabel: 'Sähköposti',
  contactMessage: 'Mitä tarvitset?',
  contactSend: 'Lähetä viesti',
  contactSending: 'Lähetetään…',
  contactSent: 'Lähetetty. Vastaamme sähköpostiisi.',
  contactError: 'Lähetys ei onnistunut. Yritä uudelleen tai lähetä suoraan sähköpostia.',
  footerTag: 'Ohjelmistostudio Helsingissä. Sivut, sovellukset, SEO, markkinointi ja ylläpito.',
  footerColServices: 'Palvelut',
  footerColPackages: 'Paketit',
  footerColContact: 'Yhteys',
  footerLegal: '© Fintoke. Kaikki oikeudet pidätetään.',
};

export const LANDING_COPY = { en, fi };

export const HERO_TAGS = {
  en: [
    { side: 'left' as const, label: 'Web apps' },
    { side: 'left' as const, label: 'Automation' },
    { side: 'left' as const, label: 'AI agents' },
    { side: 'left' as const, label: 'Integrations' },
    { side: 'right' as const, label: 'CMS' },
    { side: 'right' as const, label: 'SEO' },
    { side: 'right' as const, label: 'Maintenance' },
    { side: 'right' as const, label: 'Web coding' },
  ],
  fi: [
    { side: 'left' as const, label: 'Web-sovellukset' },
    { side: 'left' as const, label: 'Automaatio' },
    { side: 'left' as const, label: 'AI-agentit' },
    { side: 'left' as const, label: 'Integraatiot' },
    { side: 'right' as const, label: 'CMS' },
    { side: 'right' as const, label: 'SEO' },
    { side: 'right' as const, label: 'Ylläpito' },
    { side: 'right' as const, label: 'Web-koodaus' },
  ],
};
