import type { WebsiteTemplate } from './types';

/**
 * Original Claudable starters inspired by the public niche list at
 * https://github.com/cekuu35/nextjs-website-templates
 * That repo is a demo catalog, not redistributable source — these files are new.
 */
export const WEBSITE_TEMPLATES: WebsiteTemplate[] = [
  {
    id: 'modern-saas',
    name: 'Modern SaaS',
    niche: 'SaaS / Software',
    category: 'saas-tech',
    description: 'Dark product landing with feature grid, pricing, and a dashboard mock.',
    keywords: ['saas', 'software', 'dashboard', 'b2b', 'subscription', 'platform', 'product'],
    layout: 'saas-dark',
    theme: {
      mode: 'dark',
      primary: '#6366f1',
      accent: '#22d3ee',
      background: '#07070f',
      surface: '#12121c',
      text: '#f8fafc',
      muted: '#94a3b8',
      font: 'tech',
      radius: 'rounded',
    },
    brand: {
      name: 'Northlane',
      tagline: 'Operations software that stays out of the way',
      description: 'Northlane helps growing teams plan work, track delivery, and see the whole business in one calm dashboard.',
    },
    hero: {
      eyebrow: 'Workflow OS',
      title: 'Ship the week you planned, not the week that happened to you.',
      subtitle: 'A focused workspace for product, ops, and customer teams. Fewer tabs, clearer owners, live status.',
      cta: 'Start a workspace',
      ctaSecondary: 'See product tour',
    },
    stats: [
      { value: '12k+', label: 'Teams onboarded' },
      { value: '4.9', label: 'Average rating' },
      { value: '38%', label: 'Faster cycle time' },
    ],
    features: [
      { title: 'Living roadmap', body: 'Tie strategy to the work on the board without another planning ritual.' },
      { title: 'Shared status', body: 'Customers, sales, and delivery see the same truth — no status-meeting theater.' },
      { title: 'Quiet automation', body: 'Handoffs, reminders, and reports run in the background until they need you.' },
      { title: 'Workspace insights', body: 'See bottlenecks by team, not vanity charts nobody trusts.' },
    ],
    testimonials: [
      { quote: 'We stopped running three tools to answer “what’s shipping?”', name: 'Amelia Cho', role: 'VP Product, Latticework' },
      { quote: 'The dashboard looks like a product, not a spreadsheet wearing a UI.', name: 'Jonas Berg', role: 'COO, Harborline' },
    ],
    pricing: [
      { name: 'Start', price: '$29', period: '/mo', features: ['Up to 8 seats', 'Core boards', 'Email support'] },
      { name: 'Scale', price: '$79', period: '/mo', features: ['Unlimited seats', 'Insights', 'SSO', 'Priority support'], highlighted: true },
      { name: 'Enterprise', price: 'Talk', period: '', features: ['Security review', 'Data residency', 'Dedicated CSM'] },
    ],
    team: [
      { name: 'Lina Ortiz', role: 'Founder', bio: 'Previously ops lead at a Series B logistics company.' },
      { name: 'Kenji Sato', role: 'Design', bio: 'Obsessed with making dense software feel light.' },
    ],
    pages: [
      { slug: 'features', label: 'Features', kind: 'features', title: 'Everything in the workspace', subtitle: 'The pieces teams actually use after week one.' },
      { slug: 'pricing', label: 'Pricing', kind: 'pricing', title: 'Simple plans', subtitle: 'Start small. Move up when the workspace becomes the source of truth.' },
      { slug: 'integrations', label: 'Integrations', kind: 'list', title: 'Plays well with the stack you already have', subtitle: 'Connect the tools your team will not give up.', items: [
        { title: 'Slack', body: 'Status changes and mentions land where people already live.' },
        { title: 'GitHub', body: 'Pull requests map to the work they belong to.' },
        { title: 'HubSpot', body: 'Customer context sits next to delivery, not in another tab.' },
      ] },
      { slug: 'blog', label: 'Blog', kind: 'list', title: 'Notes from the product', subtitle: 'How we think about software that people open every morning.', items: [
        { title: 'Status should be a byproduct', body: 'If you need a meeting to know the state of work, the system failed.', meta: 'Product' },
        { title: 'Dashboards nobody trusts', body: 'Pretty charts are easy. Shared definitions are the work.', meta: 'Ops' },
      ] },
      { slug: 'contact', label: 'Contact', kind: 'contact', title: 'Talk to us', subtitle: 'Product questions, security reviews, or a 20-minute walkthrough.' },
    ],
    cta: { title: 'Get a quieter week.', subtitle: 'Spin up a workspace and invite the people who currently live in spreadsheets.', button: 'Create workspace' },
    footer: 'Northlane is a fictional product used as a starting template.',
  },
  {
    id: 'ai-startup',
    name: 'AI Startup',
    niche: 'AI / Machine Learning',
    category: 'saas-tech',
    description: 'High-contrast AI product site with research tone and launch CTAs.',
    keywords: ['ai', 'artificial intelligence', 'ml', 'machine learning', 'gpt', 'model', 'agent'],
    layout: 'saas-dark',
    theme: {
      mode: 'dark',
      primary: '#a3e635',
      accent: '#38bdf8',
      background: '#05080a',
      surface: '#0d1618',
      text: '#f4fce8',
      muted: '#9cb0a8',
      font: 'display',
      radius: 'sharp',
    },
    brand: {
      name: 'Helixline',
      tagline: 'Research-grade models, product-grade UX',
      description: 'Helixline builds applied language systems for teams that need accuracy they can audit.',
    },
    hero: {
      eyebrow: 'Applied research',
      title: 'Language systems you can actually put in front of customers.',
      subtitle: 'Fine-tuned models, evaluation harnesses, and a studio for iterating without a research internship.',
      cta: 'Request access',
      ctaSecondary: 'Read the approach',
    },
    stats: [
      { value: '99.1%', label: 'Eval pass rate' },
      { value: '40ms', label: 'p95 latency' },
      { value: 'SOC2', label: 'In progress' },
    ],
    features: [
      { title: 'Grounded outputs', body: 'Citations and source traces on every generation that matters.' },
      { title: 'Eval studio', body: 'Golden sets, regressions, and human review in one loop.' },
      { title: 'Private fine-tunes', body: 'Your data stays in your tenancy. Weights never train the public model.' },
      { title: 'Policy layer', body: 'Refuse, redact, and route before a token ever hits production.' },
    ],
    testimonials: [
      { quote: 'We replaced a pile of notebooks with something legal would sign off on.', name: 'Priya Nair', role: 'Head of ML, Clearspan' },
      { quote: 'The eval view is the first AI product our PMs actually open.', name: 'Owen Blake', role: 'CTO, Parcelmint' },
    ],
    pricing: [
      { name: 'Studio', price: '$99', period: '/mo', features: ['1 workspace', 'Eval sets', 'API access'] },
      { name: 'Team', price: '$399', period: '/mo', features: ['SSO', 'Fine-tunes', 'Priority GPU'], highlighted: true },
      { name: 'Lab', price: 'Custom', period: '', features: ['VPC', 'On-prem options', 'Research partnership'] },
    ],
    team: [
      { name: 'Marta Voss', role: 'CEO', bio: 'Ex-research engineer, now allergic to demo-ware.' },
      { name: 'Eli Park', role: 'Science', bio: 'Evaluation first, then architecture.' },
    ],
    pages: [
      { slug: 'product', label: 'Product', kind: 'features', title: 'The studio', subtitle: 'From prompt to production with receipts.' },
      { slug: 'pricing', label: 'Pricing', kind: 'pricing', title: 'Access', subtitle: 'Start in the studio. Graduate to private models.' },
      { slug: 'about', label: 'About', kind: 'about', title: 'Built by people who shipped models, not decks', subtitle: 'Helixline started as an internal eval stack. The product is that stack, cleaned up.' },
      { slug: 'blog', label: 'Journal', kind: 'list', title: 'Lab notes', subtitle: 'What we are measuring this month.', items: [
        { title: 'Evals that survive a product manager', body: 'If a metric cannot be explained in one sentence, it will not be used.', meta: 'Research' },
        { title: 'Latency is a product feature', body: 'Users forgive a wrong answer less than a slow one. We optimize both.', meta: 'Engineering' },
      ] },
      { slug: 'contact', label: 'Contact', kind: 'contact', title: 'Start a conversation', subtitle: 'Security questionnaires welcome. Hype decks less so.' },
    ],
    cta: { title: 'Put a model in production with receipts.', subtitle: 'We’ll walk through your eval set and whether Helixline is even the right fit.', button: 'Book a working session' },
    footer: 'Helixline is placeholder copy for an AI product template.',
  },
  {
    id: 'mobile-app',
    name: 'Mobile App Promo',
    niche: 'App landing',
    category: 'saas-tech',
    description: 'Bright app-store style landing with how-it-works and download CTAs.',
    keywords: ['mobile', 'app', 'ios', 'android', 'download', 'app store'],
    layout: 'app-promo',
    theme: {
      mode: 'light',
      primary: '#2563eb',
      accent: '#f97316',
      background: '#f8fbff',
      surface: '#ffffff',
      text: '#0f172a',
      muted: '#64748b',
      font: 'sans',
      radius: 'pill',
    },
    brand: {
      name: 'Lumenlist',
      tagline: 'A calmer to-do app for people with too many tabs',
      description: 'Lumenlist turns messy day plans into one list that actually closes.',
    },
    hero: {
      eyebrow: 'Now on iOS & Android',
      title: 'The list you’ll actually finish.',
      subtitle: 'Capture on the run, plan tonight, and get a gentle nudge — not a guilt trip — when the day slips.',
      cta: 'Download the app',
      ctaSecondary: 'Watch 30s demo',
    },
    stats: [
      { value: '2.1M', label: 'Downloads' },
      { value: '4.8★', label: 'App Store' },
      { value: '11', label: 'Languages' },
    ],
    features: [
      { title: 'Capture in two taps', body: 'Share sheet, widget, or voice. Get it out of your head.' },
      { title: 'Today vs later', body: 'A hard limit on “today” so the list stays honest.' },
      { title: 'Shared lists', body: 'Groceries, trips, and family chores without a group chat spiral.' },
      { title: 'Offline first', body: 'Works on the subway. Syncs when it can.' },
    ],
    testimonials: [
      { quote: 'The first to-do app that did not make me feel behind by 9am.', name: 'Sofia R.', role: 'App Store review' },
      { quote: 'We run our studio on one shared list. Embarrassingly simple.', name: 'Noah K.', role: 'Product designer' },
    ],
    pricing: [
      { name: 'Free', price: '$0', features: ['Personal lists', 'Widgets', 'Reminders'] },
      { name: 'Plus', price: '$4.99', period: '/mo', features: ['Unlimited shared lists', 'Themes', 'CSV export'], highlighted: true },
    ],
    team: [
      { name: 'Hana Lee', role: 'Maker', bio: 'Built Lumenlist after drowning in three other list apps.' },
    ],
    pages: [
      { slug: 'features', label: 'Features', kind: 'features', title: 'Small features, daily use', subtitle: 'Nothing clever. Everything reachable with a thumb.' },
      { slug: 'how-it-works', label: 'How it works', kind: 'list', title: 'Three steps, then you forget the app exists', subtitle: 'That’s the point.', items: [
        { title: '1. Dump', body: 'Inbox anything. Sort later.' },
        { title: '2. Pick today', body: 'Five things, not fifty.' },
        { title: '3. Close the loop', body: 'Done items archive themselves. Tomorrow starts clean.' },
      ] },
      { slug: 'pricing', label: 'Pricing', kind: 'pricing', title: 'Free to try', subtitle: 'Plus is optional. The core list is not a demo.' },
      { slug: 'download', label: 'Download', kind: 'contact', title: 'Get Lumenlist', subtitle: 'We’ll email App Store and Play links — or grab them on this page in the real build.' },
    ],
    cta: { title: 'Make tonight’s list the last one.', subtitle: 'Download Lumenlist and leave the other apps unopened tomorrow.', button: 'Get the app' },
    footer: 'Lumenlist is a fictional app used as a mobile landing template.',
  },
  {
    id: 'digital-agency',
    name: 'Digital Agency',
    niche: 'Agency / Creative',
    category: 'agency-portfolio',
    description: 'Bold typographic agency site with case studies and services.',
    keywords: ['agency', 'studio', 'creative', 'branding', 'marketing', 'design studio'],
    layout: 'agency',
    theme: {
      mode: 'dark',
      primary: '#f43f5e',
      accent: '#ffffff',
      background: '#0a0a0a',
      surface: '#161616',
      text: '#fafafa',
      muted: '#a3a3a3',
      font: 'display',
      radius: 'sharp',
    },
    brand: {
      name: 'Fold & Signal',
      tagline: 'Brand, web, and campaigns for companies that have something to say',
      description: 'An independent studio pairing strategy with craft. We make work that can survive a screenshot.',
    },
    hero: {
      eyebrow: 'Studio',
      title: 'Make it unmistakable.',
      subtitle: 'We design identities, sites, and campaigns for teams who are done looking like their category.',
      cta: 'See selected work',
      ctaSecondary: 'Start a brief',
    },
    stats: [
      { value: '11', label: 'Years' },
      { value: '90+', label: 'Launches' },
      { value: '18', label: 'Awards we still like' },
    ],
    features: [
      { title: 'Brand systems', body: 'Voice, type, color, and rules a team can actually keep.' },
      { title: 'Web experiences', body: 'Marketing sites with motion, not template fatigue.' },
      { title: 'Campaigns', body: 'A launch that has a point of view, not just a media plan.' },
      { title: 'Retainers', body: 'A senior pod on call when the product ships every two weeks.' },
    ],
    testimonials: [
      { quote: 'They treated our category as a problem, not a moodboard.', name: 'Ivy Chen', role: 'CMO, Sable Goods' },
      { quote: 'The site still looks expensive two redesign cycles later.', name: 'Marc DeWitt', role: 'Founder, Kite & Co' },
    ],
    pricing: [],
    team: [
      { name: 'Ada Moreau', role: 'Creative director', bio: 'Starts with the sentence, then the type.' },
      { name: 'Rafi Ahmed', role: 'Design director', bio: 'Motion, grids, and saying no to extra pages.' },
      { name: 'Tess Okonkwo', role: 'Strategy', bio: 'Interviews until the brief is honest.' },
    ],
    pages: [
      { slug: 'work', label: 'Work', kind: 'gallery', title: 'Selected work', subtitle: 'A few launches we still stand behind.' },
      { slug: 'services', label: 'Services', kind: 'features', title: 'What we do', subtitle: 'Brand, web, campaign. Not “full service everything”.' },
      { slug: 'about', label: 'About', kind: 'about', title: 'A small studio with a long memory', subtitle: 'Fold & Signal is twelve people in Helsinki and Lisbon. We take a few clients at a time.' },
      { slug: 'contact', label: 'Contact', kind: 'contact', title: 'Start a brief', subtitle: 'Tell us what you are launching and when it has to be real.' },
    ],
    cta: { title: 'If the category already looks like this, don’t hire us to match it.', subtitle: 'Send the brief. We’ll say if we’re the wrong studio.', button: 'Start a conversation' },
    footer: 'Fold & Signal is fictional studio copy for an agency template.',
  },
  {
    id: 'photography',
    name: 'Photography Portfolio',
    niche: 'Photography',
    category: 'agency-portfolio',
    description: 'Quiet editorial portfolio with galleries, packages, and booking.',
    keywords: ['photo', 'photography', 'portfolio', 'photographer', 'gallery', 'wedding'],
    layout: 'editorial',
    theme: {
      mode: 'light',
      primary: '#1c1917',
      accent: '#b45309',
      background: '#f5f0e8',
      surface: '#fffdf8',
      text: '#1c1917',
      muted: '#78716c',
      font: 'editorial',
      radius: 'sharp',
    },
    brand: {
      name: 'Elena Varga',
      tagline: 'Portraits and places, mostly in available light',
      description: 'Editorial and personal work across Finland and southern Europe. Film and digital.',
    },
    hero: {
      eyebrow: 'Photographer',
      title: 'Quiet pictures of loud days.',
      subtitle: 'Weddings, portraits, and assignments. The work is about people in rooms, not poses on a backdrop.',
      cta: 'View galleries',
      ctaSecondary: 'Inquire',
    },
    stats: [
      { value: '10 yrs', label: 'Working' },
      { value: 'EU', label: 'Based & traveling' },
      { value: 'Film + digital', label: 'Formats' },
    ],
    features: [
      { title: 'Weddings', body: 'A full day, a small team, and pictures that still feel like the room.' },
      { title: 'Portraits', body: 'Studio or location. Short sessions, no costume drama.' },
      { title: 'Editorial', body: 'Magazines and brands that want photographs, not stock energy.' },
      { title: 'Prints', body: 'A rotating selection from the personal archive.' },
    ],
    testimonials: [
      { quote: 'It felt like a friend was there, then the pictures were better than the day.', name: 'Mira & Tomas', role: 'Helsinki wedding' },
      { quote: 'She waited for the real expression. That’s rare.', name: 'Anja Feld', role: 'Editor, Kinfolk-adj.' },
    ],
    pricing: [
      { name: 'Portrait', price: '€450', features: ['90 minutes', '20 edits', 'Print release'] },
      { name: 'Wedding', price: '€3,200', features: ['10 hours', 'Second shooter', 'Online gallery'], highlighted: true },
      { name: 'Editorial', price: 'On request', features: ['Day rate', 'Usage license', 'Raw on request'] },
    ],
    team: [],
    pages: [
      { slug: 'gallery', label: 'Gallery', kind: 'gallery', title: 'Selected frames', subtitle: 'A mix of commissions and personal work. Color studies, not a catalog.' },
      { slug: 'about', label: 'About', kind: 'about', title: 'Hello — I’m Elena', subtitle: 'I photograph people in the light they actually live in. Based in Helsinki, available in Europe.' },
      { slug: 'packages', label: 'Packages', kind: 'pricing', title: 'Working together', subtitle: 'Numbers are starting points. Travel and usage change the rest.' },
      { slug: 'booking', label: 'Booking', kind: 'contact', title: 'Dates and details', subtitle: 'Share the day, the place, and what you hope the pictures will hold.' },
    ],
    cta: { title: 'If the light is good, let’s use it.', subtitle: 'A few sentences about the day is enough to start.', button: 'Send an inquiry' },
    footer: 'Elena Varga is a fictional photographer for this portfolio template.',
  },
  {
    id: 'personal-cv',
    name: 'Personal CV',
    niche: 'Portfolio / Resume',
    category: 'agency-portfolio',
    description: 'Clean personal site with resume, projects, writing, and contact.',
    keywords: ['cv', 'resume', 'portfolio', 'personal', 'developer', 'designer', 'about me'],
    layout: 'cv',
    theme: {
      mode: 'light',
      primary: '#1e3a5f',
      accent: '#c2410c',
      background: '#f7f6f3',
      surface: '#ffffff',
      text: '#1c1917',
      muted: '#57534e',
      font: 'sans',
      radius: 'rounded',
    },
    brand: {
      name: 'Aaro Niemi',
      tagline: 'Product designer & occasional frontend',
      description: 'I design software that has to survive real workweeks — currently in Helsinki.',
    },
    hero: {
      eyebrow: 'Available Q4',
      title: 'I design products people can finish their jobs in.',
      subtitle: 'Eight years across B2B tools and public services. I care about information density, writing, and not decorating broken flows.',
      cta: 'See selected work',
      ctaSecondary: 'Download CV',
    },
    stats: [
      { value: '8 yrs', label: 'Experience' },
      { value: 'B2B + civic', label: 'Domains' },
      { value: 'FI / EN', label: 'Languages' },
    ],
    features: [
      { title: 'Product design', body: 'Flows, systems, and the unglamorous IA in between.' },
      { title: 'Design engineering', body: 'Enough frontend to ship the prototype instead of describing it.' },
      { title: 'Research', body: 'Interviews, support logs, and sitting with the people who do the work.' },
      { title: 'Writing', body: 'Interface copy and the longer notes that keep a team aligned.' },
    ],
    testimonials: [
      { quote: 'Aaro made the tool feel like it respected the job.', name: 'Sari Hämäläinen', role: 'Head of Ops' },
      { quote: 'The only designer who rewrote the empty states without being asked.', name: 'Leo Grant', role: 'Engineering manager' },
    ],
    pricing: [],
    team: [],
    pages: [
      { slug: 'work', label: 'Work', kind: 'list', title: 'Selected projects', subtitle: 'A few pieces with enough context to be useful.', items: [
        { title: 'Harborline ops console', body: 'Redesigned exception handling for a logistics control room. Cut time-to-decision.', meta: '2025' },
        { title: 'Civic benefits form', body: 'Rebuilt a 40-field application into a paced, saveable flow.', meta: '2024' },
        { title: 'Northlane marketing', body: 'Design system and site for a SaaS launch.', meta: '2024' },
      ] },
      { slug: 'about', label: 'Resume', kind: 'about', title: 'Background', subtitle: 'Helsinki-based. Previously at a public-sector digital team and two product companies.' },
      { slug: 'notes', label: 'Notes', kind: 'list', title: 'Writing', subtitle: 'Short notes on software that has to work on a Monday.', items: [
        { title: 'Density is kindness', body: 'Power users should not click five times to see the number they came for.' },
        { title: 'Empty states are the product', body: 'If the first screen is a blank table, you already lost.' },
      ] },
      { slug: 'contact', label: 'Contact', kind: 'contact', title: 'Say hello', subtitle: 'Roles, collaborations, and interesting messes.' },
    ],
    cta: { title: 'Let’s see if the work overlaps.', subtitle: 'A paragraph about the problem is better than a generic role spec.', button: 'Email me' },
    footer: 'Aaro Niemi is fictional CV copy for a personal site template.',
  },
  {
    id: 'restaurant-cafe',
    name: 'Restaurant & Cafe',
    niche: 'Restaurant / Cafe',
    category: 'food-hospitality',
    description: 'Warm cafe site with menu, gallery, story, and reservations.',
    keywords: ['restaurant', 'cafe', 'coffee', 'bistro', 'menu', 'food', 'bakery'],
    layout: 'hospitality',
    theme: {
      mode: 'light',
      primary: '#9a3412',
      accent: '#b45309',
      background: '#fff7ed',
      surface: '#ffedd5',
      text: '#431407',
      muted: '#9a3412',
      font: 'serif',
      radius: 'rounded',
    },
    brand: {
      name: 'Kaarna',
      tagline: 'All-day kitchen in Kallio',
      description: 'Bread in the morning, wine in the evening. A neighbourhood room with a serious kitchen.',
    },
    hero: {
      eyebrow: 'Kallio, Helsinki',
      title: 'Come in for coffee. Stay for whatever the oven is doing.',
      subtitle: 'Seasonal plates, natural wine, and a pastry case that empties before lunch. Walk-ins welcome until we fill up.',
      cta: 'Reserve a table',
      ctaSecondary: 'See today’s menu',
    },
    stats: [
      { value: 'Tue–Sun', label: 'Open' },
      { value: '08–23', label: 'Hours' },
      { value: '18', label: 'Seats inside' },
    ],
    features: [
      { title: 'Morning', body: 'Cardamom buns, filter coffee, and newspapers nobody has to share.' },
      { title: 'Lunch', body: 'One pot, one salad, one sweet. Changes with the market.' },
      { title: 'Evening', body: 'A short menu, a longer wine list, candles if the room asks for them.' },
      { title: 'Takeaway', body: 'Loaves and leftovers at the counter after 4.' },
    ],
    testimonials: [
      { quote: 'The kind of place you take visiting friends so they understand the city.', name: 'Elina P.', role: 'Neighbour' },
      { quote: 'I came for the bun. I now have a usual table.', name: 'Chris T.', role: 'Regular' },
    ],
    pricing: [],
    team: [
      { name: 'Maija Koskinen', role: 'Chef', bio: 'Previously at a tiny place in Turku. Obsessed with broths.' },
      { name: 'Omar Haddad', role: 'Front of house', bio: 'Remembers how you take your coffee after two visits.' },
    ],
    pages: [
      { slug: 'menu', label: 'Menu', kind: 'list', title: 'From the kitchen', subtitle: 'A sample evening menu. The real one is on the board.', items: [
        { title: 'Roasted carrots, brown butter, rye', body: 'From the farm in Nurmijärvi.', meta: '12' },
        { title: 'Pike-perch, fennel, mussel sauce', body: 'Dayboat, when we can get it.', meta: '26' },
        { title: 'Chocolate, sea buckthorn, malt', body: 'The dessert people argue about.', meta: '11' },
      ] },
      { slug: 'gallery', label: 'Gallery', kind: 'gallery', title: 'The room', subtitle: 'Wood, steam, and the street in the window.' },
      { slug: 'about', label: 'About', kind: 'about', title: 'A neighbourhood kitchen', subtitle: 'Kaarna opened in 2021 in a former print shop. We cook what the week gives us.' },
      { slug: 'reservation', label: 'Reservation', kind: 'contact', title: 'Book a table', subtitle: 'Parties of 1–6. Larger groups by email. Dogs on the terrace in summer.' },
    ],
    cta: { title: 'We’ll keep a table if you ask nicely.', subtitle: 'Weekends fill up. Midweek is for lingering.', button: 'Reserve' },
    footer: 'Kaarna is a fictional restaurant for this hospitality template.',
  },
  {
    id: 'fine-dining',
    name: 'Restaurant Reservation',
    niche: 'Fine dining',
    category: 'food-hospitality',
    description: 'Dark luxury dining site with tasting menu and reservation flow.',
    keywords: ['fine dining', 'tasting menu', 'michelin', 'reservation', 'chef'],
    layout: 'luxury',
    theme: {
      mode: 'dark',
      primary: '#d4af37',
      accent: '#f5e6c8',
      background: '#0c0a09',
      surface: '#1c1917',
      text: '#fafaf9',
      muted: '#a8a29e',
      font: 'luxury',
      radius: 'sharp',
    },
    brand: {
      name: 'Säde',
      tagline: 'A tasting room in Punavuori',
      description: 'Twenty seats. One sitting. A menu that changes when the ingredients insist.',
    },
    hero: {
      eyebrow: 'One sitting · Thursday–Saturday',
      title: 'Dinner as a single, unhurried line.',
      subtitle: 'Säde is a tasting menu built around Finnish produce and a kitchen that would rather take a night off than repeat a dull plate.',
      cta: 'Request a reservation',
      ctaSecondary: 'The menu',
    },
    stats: [
      { value: '20', label: 'Seats' },
      { value: '9', label: 'Courses' },
      { value: '19:00', label: 'Sitting' },
    ],
    features: [
      { title: 'The menu', body: 'Nine courses, optional wine pairing, a vegetarian path with notice.' },
      { title: 'The room', body: 'Low light, linen, a kitchen you can see if you want to.' },
      { title: 'The pairing', body: 'Nordic bottles and a few things we ferment ourselves.' },
      { title: 'Private nights', body: 'Buy out the room on Sundays. Write to us.' },
    ],
    testimonials: [
      { quote: 'Not theatre. Just cooking with nowhere to hide.', name: 'Review, Guest list' },
      { quote: 'We still talk about the last savoury plate.', name: 'J. & A.', role: 'Anniversary' },
    ],
    pricing: [
      { name: 'Menu', price: '€165', features: ['Nine courses', 'Dietary notes welcome'] },
      { name: 'Pairing', price: '€95', features: ['Six glasses', 'Low-alcohol option'], highlighted: true },
    ],
    team: [
      { name: 'Aino Leppänen', role: 'Chef', bio: 'Time in Copenhagen and a stubborn loyalty to Finnish winter produce.' },
    ],
    pages: [
      { slug: 'menu', label: 'Menu', kind: 'list', title: 'This week', subtitle: 'A sketch. The printed menu is the truth.', items: [
        { title: 'Archipelago, cold', body: 'Cured fish, spruce, cultured cream.' },
        { title: 'Garden, warm', body: 'Cabbage, last year’s honey, burnt onion.' },
        { title: 'Fire', body: 'Agnes the lamb, or not, depending on the farm.' },
      ] },
      { slug: 'about', label: 'House', kind: 'about', title: 'A small room on purpose', subtitle: 'We cook for twenty because that is how many plates we can finish properly.' },
      { slug: 'reservation', label: 'Reservation', kind: 'contact', title: 'Request a night', subtitle: 'We confirm by email with a reference number. A card holds the table.' },
      { slug: 'contact', label: 'Contact', kind: 'contact', title: 'Write to the house', subtitle: 'Press, private sittings, suppliers.' },
    ],
    cta: { title: 'If you can be on time, we can cook.', subtitle: 'Reservations for the next sitting open on the first of the month.', button: 'Request a table' },
    footer: 'Säde is fictional fine-dining copy for this template.',
  },
  {
    id: 'hotel-booking',
    name: 'Hotel Booking',
    niche: 'Hotel / Hospitality',
    category: 'food-hospitality',
    description: 'Calm hotel site with rooms, amenities, gallery, and booking.',
    keywords: ['hotel', 'boutique hotel', 'booking', 'rooms', 'stay', 'hospitality'],
    layout: 'hospitality',
    theme: {
      mode: 'light',
      primary: '#3f6212',
      accent: '#44403c',
      background: '#f4f1ea',
      surface: '#ffffff',
      text: '#1c1917',
      muted: '#57534e',
      font: 'serif',
      radius: 'rounded',
    },
    brand: {
      name: 'Villa Aalto',
      tagline: 'A small hotel by the water in Espoo',
      description: 'Twelve rooms, a sauna that faces the pines, and breakfast that does not come from a tray line.',
    },
    hero: {
      eyebrow: 'Espoo archipelago',
      title: 'Sleep next to the trees. Wake next to the water.',
      subtitle: 'Villa Aalto is a converted 1930s house. Rooms are quiet. The sauna is not optional.',
      cta: 'Check availability',
      ctaSecondary: 'View rooms',
    },
    stats: [
      { value: '12', label: 'Rooms' },
      { value: 'Sauna', label: 'Every evening' },
      { value: '25 min', label: 'To Helsinki' },
    ],
    features: [
      { title: 'Rooms', body: 'Linen, dark wood, and windows that actually open.' },
      { title: 'Sauna', body: 'Wood-fired, lake path, towels that are not an afterthought.' },
      { title: 'Kitchen', body: 'Breakfast until 11. Dinner on Fridays if you book it.' },
      { title: 'Work, if you must', body: 'Fast wifi. A desk in four of the rooms. We will not judge.' },
    ],
    testimonials: [
      { quote: 'The quietest night we’ve had within reach of the airport.', name: 'Dana & Will', role: 'Two nights in March' },
      { quote: 'They treated the sauna like the main event. Correct.', name: 'Mikko R.', role: 'Guest' },
    ],
    pricing: [
      { name: 'Pine', price: '€180', period: '/night', features: ['Queen', 'Garden view', 'Breakfast'] },
      { name: 'Water', price: '€240', period: '/night', features: ['King', 'Lake view', 'Desk'], highlighted: true },
      { name: 'House suite', price: '€320', period: '/night', features: ['Separate sitting room', 'Bathtub'] },
    ],
    team: [
      { name: 'Saara V.', role: 'Host', bio: 'Lives on the property. Knows the ferry times by heart.' },
    ],
    pages: [
      { slug: 'rooms', label: 'Rooms', kind: 'list', title: 'Where you’ll sleep', subtitle: 'Every room has blackout, a kettle, and a chair by the window.', items: [
        { title: 'Pine', body: 'Garden side. Morning light. Queen bed.', meta: 'from €180' },
        { title: 'Water', body: 'Lake side. Desk. King bed.', meta: 'from €240' },
        { title: 'House suite', body: 'The old sitting room, now yours.', meta: 'from €320' },
      ] },
      { slug: 'amenities', label: 'Amenities', kind: 'features', title: 'The house', subtitle: 'Sauna, rowing boat in summer, library nobody has catalogued.' },
      { slug: 'gallery', label: 'Gallery', kind: 'gallery', title: 'Light through the pines', subtitle: 'A few honest pictures. The lake does the rest.' },
      { slug: 'booking', label: 'Booking', kind: 'contact', title: 'Check a date', subtitle: 'We’ll confirm within a day. Two-night minimum on weekends.' },
    ],
    cta: { title: 'Come when the week is too loud.', subtitle: 'Tell us the dates and whether you want the sauna reserved.', button: 'Request a stay' },
    footer: 'Villa Aalto is a fictional hotel for this booking template.',
  },
  {
    id: 'fitness-gym',
    name: 'Fitness & Gym',
    niche: 'Gym / Sports',
    category: 'health-wellness',
    description: 'High-energy gym site with classes, schedule, trainers, and membership.',
    keywords: ['gym', 'fitness', 'workout', 'training', 'crossfit', 'yoga', 'studio'],
    layout: 'fitness',
    theme: {
      mode: 'dark',
      primary: '#a3e635',
      accent: '#f97316',
      background: '#09090b',
      surface: '#18181b',
      text: '#fafafa',
      muted: '#a1a1aa',
      font: 'display',
      radius: 'sharp',
    },
    brand: {
      name: 'BASE 12',
      tagline: 'Strength, conditioning, no soundtrack of shouting',
      description: 'A training floor in Vallila for people who want to get stronger and still walk to work after.',
    },
    hero: {
      eyebrow: 'Vallila · Open 06–22',
      title: 'Show up. Lift. Leave better than you arrived.',
      subtitle: 'Small classes, serious programming, and coaches who can explain the why. Drop-ins welcome.',
      cta: 'Start a trial week',
      ctaSecondary: 'See the schedule',
    },
    stats: [
      { value: '18', label: 'Classes / week' },
      { value: '12', label: 'Cap per class' },
      { value: '06:00', label: 'First session' },
    ],
    features: [
      { title: 'Strength', body: 'Barbell cycles with room to actually recover.' },
      { title: 'Conditioning', body: 'Short, ugly, effective. Not a dance class with kettlebells.' },
      { title: 'Foundations', body: 'If you are new, we start here. Ego stays in the locker.' },
      { title: 'Open floor', body: 'Members lift on their own between classes.' },
    ],
    testimonials: [
      { quote: 'First gym that programmed me like an adult, not a montage.', name: 'Tuomas K.' },
      { quote: 'I can still climb stairs after leg day. That’s coaching.', name: 'Riikka S.' },
    ],
    pricing: [
      { name: 'Drop-in', price: '€22', features: ['One class', 'Gear included'] },
      { name: 'Unlimited', price: '€89', period: '/mo', features: ['All classes', 'Open floor', 'Sauna'], highlighted: true },
      { name: '4-pack', price: '€72', features: ['Used within 6 weeks'] },
    ],
    team: [
      { name: 'Jere Mäkinen', role: 'Head coach', bio: 'Powerlifting background. Calm voice, heavy bar.' },
      { name: 'Nina Solberg', role: 'Coach', bio: 'Conditioning and the people who think they hate it.' },
    ],
    pages: [
      { slug: 'classes', label: 'Classes', kind: 'features', title: 'What we run', subtitle: 'Strength, conditioning, foundations. That’s the menu.' },
      { slug: 'schedule', label: 'Schedule', kind: 'list', title: 'This week', subtitle: 'Times shift slightly on holidays. The board in the gym is canonical.', items: [
        { title: 'Mon / Wed / Fri', body: '06:15 Strength · 12:10 Lunch lift · 17:30 Conditioning', meta: '60 min' },
        { title: 'Tue / Thu', body: '07:00 Foundations · 18:00 Strength', meta: '55 min' },
        { title: 'Sat', body: '10:00 Mixed long session', meta: '75 min' },
      ] },
      { slug: 'trainers', label: 'Coaches', kind: 'team', title: 'Who’s on the floor', subtitle: 'You’ll see the same faces. That’s the point.' },
      { slug: 'membership', label: 'Membership', kind: 'pricing', title: 'Join the floor', subtitle: 'Trial week is €29. Cancel anytime in the first month.' },
      { slug: 'contact', label: 'Contact', kind: 'contact', title: 'Come in or write', subtitle: 'The door code for members is in the welcome mail. Visitors, ring.' },
    ],
    cta: { title: 'Your first week is a trial, not a trap.', subtitle: 'Book a foundations class. We’ll see if the programming fits.', button: 'Start trial week' },
    footer: 'BASE 12 is a fictional gym for this fitness template.',
  },
  {
    id: 'dental-clinic',
    name: 'Dental Clinic',
    niche: 'Healthcare / Dental',
    category: 'health-wellness',
    description: 'Trust-forward clinic site with treatments, team, and appointments.',
    keywords: ['dental', 'dentist', 'clinic', 'teeth', 'healthcare', 'medical', 'doctor'],
    layout: 'medical',
    theme: {
      mode: 'light',
      primary: '#0f766e',
      accent: '#0369a1',
      background: '#f8fafc',
      surface: '#ffffff',
      text: '#0f172a',
      muted: '#475569',
      font: 'sans',
      radius: 'rounded',
    },
    brand: {
      name: 'Aava Dental',
      tagline: 'Calm dentistry in Töölö',
      description: 'A small practice for check-ups, restorations, and people who have been avoiding the chair.',
    },
    hero: {
      eyebrow: 'Töölö · Mon–Fri',
      title: 'Dentistry that explains itself before it starts.',
      subtitle: 'We take time on the plan, use modern anaesthesia, and never upsell a tray of extras you did not ask for.',
      cta: 'Book an appointment',
      ctaSecondary: 'Our treatments',
    },
    stats: [
      { value: '15 min', label: 'From Kamppi' },
      { value: '2', label: 'Treatment rooms' },
      { value: 'EN / FI', label: 'Languages' },
    ],
    features: [
      { title: 'Check-ups', body: 'Unhurried exams, clear photos, a plan you can take home.' },
      { title: 'Restorations', body: 'Inlays, crowns, and work that should last.' },
      { title: 'Whitening', body: 'Only when the enamel can take it. We’ll say no if it can’t.' },
      { title: 'Anxiety visits', body: 'Longer slots, breaks whenever you need them.' },
    ],
    testimonials: [
      { quote: 'First dentist who talked me through every step without baby talk.', name: 'Laura M.' },
      { quote: 'They showed me the x-ray and the options. I chose. That was new.', name: 'Peter H.' },
    ],
    pricing: [
      { name: 'Exam', price: '€85', features: ['Check-up', 'Cleaning add-on optional'] },
      { name: 'Emergency', price: '€120', features: ['Same-week slot when possible'], highlighted: true },
    ],
    team: [
      { name: 'Dr. Emilia Saarinen', role: 'Dentist', bio: 'Restorative focus. Trained in Turku. Allergic to rush.' },
      { name: 'Veera L.', role: 'Hygienist', bio: 'The person patients actually confess to.' },
    ],
    pages: [
      { slug: 'treatments', label: 'Treatments', kind: 'list', title: 'What we do', subtitle: 'If you need oral surgery, we refer — we don’t pretend.', items: [
        { title: 'Exams & hygiene', body: 'The boring, important part. Photos included.' },
        { title: 'Fillings & crowns', body: 'Materials chosen for the tooth, not the brochure.' },
        { title: 'Whitening', body: 'After we check the gums. Not before.' },
      ] },
      { slug: 'team', label: 'Team', kind: 'team', title: 'Who you’ll meet', subtitle: 'A small practice on purpose.' },
      { slug: 'about', label: 'About', kind: 'about', title: 'A quieter clinic', subtitle: 'Aava opened so Emilia could spend more than twelve minutes per patient.' },
      { slug: 'appointment', label: 'Appointment', kind: 'contact', title: 'Book a time', subtitle: 'New patients: tell us if you’re nervous. We’ll add minutes, not a lecture.' },
    ],
    cta: { title: 'If you’ve been putting it off, start with a conversation.', subtitle: 'No pressure to book treatment on the first visit.', button: 'Request an appointment' },
    footer: 'Aava Dental is fictional clinic copy for this healthcare template.',
  },
  {
    id: 'barber-salon',
    name: 'Barber & Salon',
    niche: 'Beauty / Grooming',
    category: 'health-wellness',
    description: 'Sharp salon site with priced services, team, gallery, and booking.',
    keywords: ['barber', 'salon', 'haircut', 'hair', 'grooming', 'beauty'],
    layout: 'luxury',
    theme: {
      mode: 'dark',
      primary: '#e7c07a',
      accent: '#fafafa',
      background: '#171412',
      surface: '#231f1c',
      text: '#f5f0e8',
      muted: '#a8a29e',
      font: 'display',
      radius: 'sharp',
    },
    brand: {
      name: 'CUTROOM',
      tagline: 'Cuts, color, and a chair that doesn’t rush you',
      description: 'A four-chair room in Punavuori. Classic cuts, modern color, no upsell of twelve products.',
    },
    hero: {
      eyebrow: 'Punavuori',
      title: 'Look like yourself, on a good day.',
      subtitle: 'Book a cut, a color, or both. We work on time, keep the playlist decent, and send you out with hair you can live in.',
      cta: 'Book a chair',
      ctaSecondary: 'Services & prices',
    },
    stats: [
      { value: '4', label: 'Chairs' },
      { value: 'Tue–Sat', label: 'Open' },
      { value: '45–90m', label: 'Appointments' },
    ],
    features: [
      { title: 'Cuts', body: 'Skin fades to long layers. We cut to your hair, not the trend video.' },
      { title: 'Color', body: 'Lived-in color. No surprise orange.' },
      { title: 'Beard', body: 'Shape-up with the cut, or on its own.' },
      { title: 'Kids', body: 'Saturday mornings. Patience included.' },
    ],
    testimonials: [
      { quote: 'They asked what I do all week, then cut for that. Rare.', name: 'Aleksi' },
      { quote: 'Color that still looks like my hair, not a filter.', name: 'Noora' },
    ],
    pricing: [
      { name: 'Cut', price: '€42', features: ['45 min', 'Finish'] },
      { name: 'Cut + beard', price: '€55', features: ['60 min'], highlighted: true },
      { name: 'Color', price: 'from €95', features: ['Consultation first'] },
    ],
    team: [
      { name: 'Leo', role: 'Cuts', bio: 'Fades and the people who think they only have one haircut.' },
      { name: 'Mira', role: 'Color', bio: 'Will talk you out of a trend if it will fight your hair.' },
    ],
    pages: [
      { slug: 'services', label: 'Services', kind: 'pricing', title: 'Menu', subtitle: 'Prices include the finish. Tips are optional and never expected on card prompts.' },
      { slug: 'gallery', label: 'Gallery', kind: 'gallery', title: 'Recent chairs', subtitle: 'Real heads. Different hair. Same room.' },
      { slug: 'team', label: 'Team', kind: 'team', title: 'Who cuts', subtitle: 'Request a chair in the booking notes.' },
      { slug: 'booking', label: 'Booking', kind: 'contact', title: 'Take a chair', subtitle: 'Same-week openings exist. Walk-ins if the light is on.' },
    ],
    cta: { title: 'Your next good hair day can be on the calendar.', subtitle: 'Prefer a human? WhatsApp the shop from the confirmation mail.', button: 'Book now' },
    footer: 'CUTROOM is fictional salon copy for this template.',
  },
  {
    id: 'real-estate',
    name: 'Real Estate',
    niche: 'Property / Listings',
    category: 'business-professional',
    description: 'Listing-driven property site with filters, details, and inquiries.',
    keywords: ['real estate', 'property', 'homes', 'listings', 'apartment', 'realtor', 'housing'],
    layout: 'saas-light',
    theme: {
      mode: 'light',
      primary: '#1e3a8a',
      accent: '#b45309',
      background: '#f8fafc',
      surface: '#ffffff',
      text: '#0f172a',
      muted: '#475569',
      font: 'sans',
      radius: 'rounded',
    },
    brand: {
      name: 'Harbor Homes',
      tagline: 'Helsinki apartments with the boring details included',
      description: 'A focused brokerage for city apartments. We send the floor plan, the housing company papers, and the noisy-neighbour truth.',
    },
    hero: {
      eyebrow: 'Helsinki & Espoo',
      title: 'Find a home. Know what you’re walking into.',
      subtitle: 'Curated listings, honest notes on the building, and viewings that start on time.',
      cta: 'Browse listings',
      ctaSecondary: 'Sell with us',
    },
    stats: [
      { value: '64', label: 'Active listings' },
      { value: '12 days', label: 'Avg. to offer' },
      { value: '4.9', label: 'Client rating' },
    ],
    features: [
      { title: 'Listings that filter', body: 'Rooms, courtyard, elevator, housing company loan — the stuff that actually matters.' },
      { title: 'Building notes', body: 'Renovations done, renovations coming, and what the meeting minutes say.' },
      { title: 'Viewings', body: 'Small groups. Time to open cupboards.' },
      { title: 'Selling', body: 'Photography, staging advice, and a price based on solds, not wishes.' },
    ],
    testimonials: [
      { quote: 'They told us about the upcoming pipe reno before we fell in love.', name: 'Anna & Joona' },
      { quote: 'Sold in nine days without circus staging.', name: 'Helena K.' },
    ],
    pricing: [
      { name: 'Buyer', price: '€0', features: ['Search', 'Viewings', 'Offer support'] },
      { name: 'Seller', price: '2.5%', period: '+ VAT', features: ['Full listing', 'Photography', 'Negotiation'], highlighted: true },
    ],
    team: [
      { name: 'Otto Lindholm', role: 'Broker', bio: 'Kallio and the inner city. Walks every stairwell.' },
      { name: 'Senni Aalto', role: 'Broker', bio: 'Espoo family homes and the train-line apartments.' },
    ],
    pages: [
      { slug: 'listings', label: 'Listings', kind: 'list', title: 'On the market', subtitle: 'A sample of the kind of homes we represent. Filters come with the live build.', items: [
        { title: '2h + k, Punavuori', body: '58 m² · courtyard · elevator · housing company loan 42k', meta: '€398,000' },
        { title: '3h + k, Töölö', body: '81 m² · park side · 2022 kitchen', meta: '€612,000' },
        { title: '1h + kk, Kallio', body: '32 m² · top floor · city view if you lean', meta: '€214,000' },
      ] },
      { slug: 'about', label: 'About', kind: 'about', title: 'A smaller brokerage on purpose', subtitle: 'We take fewer listings so the notes stay true and the phone still gets answered.' },
      { slug: 'inquiry', label: 'Inquiry', kind: 'contact', title: 'Tell us what you’re looking for', subtitle: 'Budget, neighbourhoods you refuse, and whether stairs are a deal-breaker.' },
    ],
    cta: { title: 'Looking or listing — start with a straight conversation.', subtitle: 'No automated valuation gimmicks. A human will write back.', button: 'Send an inquiry' },
    footer: 'Harbor Homes is fictional brokerage copy for this template.',
  },
  {
    id: 'construction',
    name: 'Construction',
    niche: 'Construction / B2B',
    category: 'business-professional',
    description: 'Industrial contractor site with services, projects, and quote requests.',
    keywords: ['construction', 'contractor', 'building', 'renovation', 'builder'],
    layout: 'industrial',
    theme: {
      mode: 'light',
      primary: '#c2410c',
      accent: '#1e293b',
      background: '#f8fafc',
      surface: '#ffffff',
      text: '#0f172a',
      muted: '#475569',
      font: 'sans',
      radius: 'sharp',
    },
    brand: {
      name: 'Kivi & Co',
      tagline: 'Buildings that stay quiet after we leave',
      description: 'General contractor for commercial interiors and careful residential renovations in Uusimaa.',
    },
    hero: {
      eyebrow: 'Uusimaa · Since 2004',
      title: 'We build what the drawings promised.',
      subtitle: 'Fit-outs, structural repairs, and renovations where the site stays organized and the neighbours still speak to you.',
      cta: 'Request a quote',
      ctaSecondary: 'See projects',
    },
    stats: [
      { value: '20+', label: 'Years' },
      { value: '140', label: 'Handovers' },
      { value: 'A+', label: 'Safety rating' },
    ],
    features: [
      { title: 'Commercial interiors', body: 'Offices, clinics, and shops that have to open on a Monday.' },
      { title: 'Residential reno', body: 'Kitchens, wet rooms, and the pipe projects nobody wants to live through twice.' },
      { title: 'Site management', body: 'One named superintendent. Not a rotating cast.' },
      { title: 'Aftercare', body: 'A defects list we actually close.' },
    ],
    testimonials: [
      { quote: 'They treated the housing company meeting like a design review. Refreshing.', name: 'Board, As. Oy Merituuli' },
      { quote: 'Opened the clinic three days early. The only contractor story I enjoy telling.', name: 'Clinic director' },
    ],
    pricing: [],
    team: [
      { name: 'Pekka Kivi', role: 'Principal', bio: 'Still walks sites on Tuesdays.' },
      { name: 'Inka Rautio', role: 'Projects', bio: 'Schedules, neighbours, and the truth in the Gantt.' },
    ],
    pages: [
      { slug: 'services', label: 'Services', kind: 'features', title: 'What we take on', subtitle: 'If it’s only demolition, we’ll say so and introduce someone else.' },
      { slug: 'projects', label: 'Projects', kind: 'list', title: 'Recent handovers', subtitle: 'A few sites with enough context to be useful.', items: [
        { title: 'Töölö clinic fit-out', body: '420 m² · occupied building · night work', meta: '2025' },
        { title: 'Espoo housing company pipes', body: '36 apartments · 11 months · residents in place', meta: '2024' },
        { title: 'Kamppi office floor', body: 'Cat-A to Cat-B · 90 days', meta: '2024' },
      ] },
      { slug: 'about', label: 'About', kind: 'about', title: 'A contractor that still answers the phone', subtitle: 'Family-owned. Union labour. We do not bid jobs we cannot staff.' },
      { slug: 'quote', label: 'Quote', kind: 'contact', title: 'Send the drawings', subtitle: 'PDFs, a target date, and whether residents will be home. We’ll tell you if the calendar is honest.' },
    ],
    cta: { title: 'If the schedule is fantasy, we’ll say so before the contract.', subtitle: 'Quotes within five working days for complete drawing sets.', button: 'Request a quote' },
    footer: 'Kivi & Co is a fictional contractor for this template.',
  },
  {
    id: 'law-firm',
    name: 'Law Firm',
    niche: 'Legal / Professional',
    category: 'business-professional',
    description: 'Conservative firm site with practice areas, attorneys, and consultations.',
    keywords: ['law', 'lawyer', 'legal', 'attorney', 'firm', 'counsel'],
    layout: 'legal',
    theme: {
      mode: 'light',
      primary: '#1e1b4b',
      accent: '#7f1d1d',
      background: '#f7f5f0',
      surface: '#ffffff',
      text: '#1c1917',
      muted: '#57534e',
      font: 'serif',
      radius: 'sharp',
    },
    brand: {
      name: 'Rehn & Aalto',
      tagline: 'Counsel for companies and the people who run them',
      description: 'A Helsinki boutique for commercial contracts, disputes, and employment matters.',
    },
    hero: {
      eyebrow: 'Attorneys · Helsinki',
      title: 'Clear advice. Careful documents. No theatre.',
      subtitle: 'We help growing companies with the contracts and conflicts that actually move the business — and we write in sentences you can use.',
      cta: 'Request a consultation',
      ctaSecondary: 'Practice areas',
    },
    stats: [
      { value: '1998', label: 'Founded' },
      { value: '9', label: 'Lawyers' },
      { value: 'FI / EN / SV', label: 'Working languages' },
    ],
    features: [
      { title: 'Commercial', body: 'Shareholder agreements, SaaS MSAs, and the annexes everyone skips.' },
      { title: 'Disputes', body: 'When negotiation fails. We prefer the former.' },
      { title: 'Employment', body: 'Hiring, exits, and the investigations nobody wanted.' },
      { title: 'Privacy', body: 'Enough GDPR to be real, not a sticker.' },
    ],
    testimonials: [
      { quote: 'They shortened a 40-page MSA into something both sides could sign.', name: 'General counsel, Series B' },
      { quote: 'Direct. Available. Not in love with their own Latin.', name: 'Founder' },
    ],
    pricing: [
      { name: 'Consultation', price: '€280', features: ['60 minutes', 'Credited if retained'] },
    ],
    team: [
      { name: 'Maria Rehn', role: 'Partner', bio: 'Commercial and disputes. Former in-house.' },
      { name: 'Erik Aalto', role: 'Partner', bio: 'Employment and investigations.' },
      { name: 'Linnea Fors', role: 'Senior associate', bio: 'Contracts that product teams will actually read.' },
    ],
    pages: [
      { slug: 'practice', label: 'Practice', kind: 'features', title: 'Practice areas', subtitle: 'We do not pretend to be a full-service tower.' },
      { slug: 'attorneys', label: 'Attorneys', kind: 'team', title: 'The lawyers', subtitle: 'You will work with the person you meet, not a rotating junior.' },
      { slug: 'about', label: 'The firm', kind: 'about', title: 'A boutique on purpose', subtitle: 'Nine lawyers. We turn down work that would make us a different firm.' },
      { slug: 'consultation', label: 'Consultation', kind: 'contact', title: 'Request a consultation', subtitle: 'A short note on the matter is enough. Conflict checks first.' },
    ],
    cta: { title: 'If the matter is real, we will tell you quickly whether we can help.', subtitle: 'Consultations are billed, then credited if you retain us.', button: 'Write to the firm' },
    footer: 'Rehn & Aalto is fictional legal copy for this template.',
  },
  {
    id: 'online-course',
    name: 'Online Course',
    niche: 'Education / eLearning',
    category: 'education-content',
    description: 'Course platform landing with curriculum, instructor, and pricing.',
    keywords: ['course', 'education', 'learn', 'academy', 'elearning', 'class', 'bootcamp'],
    layout: 'saas-light',
    theme: {
      mode: 'light',
      primary: '#6d28d9',
      accent: '#db2777',
      background: '#faf8ff',
      surface: '#ffffff',
      text: '#1e1b4b',
      muted: '#6b21a8',
      font: 'sans',
      radius: 'rounded',
    },
    brand: {
      name: 'Field Notes Academy',
      tagline: 'Practical courses for people already on the job',
      description: 'Short, serious programs on research, writing, and product sense — built for working weeks, not campus energy.',
    },
    hero: {
      eyebrow: 'Next cohort in 3 weeks',
      title: 'Learn the part of the job nobody taught you.',
      subtitle: 'Live sessions, critique, and homework that looks like work. Not 40 hours of video you will never finish.',
      cta: 'See the courses',
      ctaSecondary: 'Meet the instructor',
    },
    stats: [
      { value: '6 wks', label: 'Typical length' },
      { value: '24', label: 'People per cohort' },
      { value: '92%', label: 'Finish rate' },
    ],
    features: [
      { title: 'Live, not infinite', body: 'A start date and an end date. Your calendar can survive it.' },
      { title: 'Critique', body: 'You ship work. Other humans respond. That’s the product.' },
      { title: 'Office hours', body: 'Bring the messy real project, not a homework clone.' },
      { title: 'Recordings', body: 'If you miss a week, you are not expelled from the decade.' },
    ],
    testimonials: [
      { quote: 'The first course that respected that I have a job.', name: 'Camila R.', role: 'PM' },
      { quote: 'I finally have a research process I can explain to engineering.', name: 'Samir D.', role: 'Designer' },
    ],
    pricing: [
      { name: 'Audit', price: '€290', features: ['Recordings', 'Materials', 'No critique'] },
      { name: 'Cohort', price: '€790', features: ['Live sessions', 'Critique', 'Office hours'], highlighted: true },
      { name: 'Team', price: '€2,400', features: ['5 seats', 'Private Slack'] },
    ],
    team: [
      { name: 'Iris Feldman', role: 'Instructor', bio: 'Research lead for twelve years. Tired of courses that are just her talking.' },
    ],
    pages: [
      { slug: 'courses', label: 'Courses', kind: 'list', title: 'Open programs', subtitle: 'One or two running at a time. We do not flood the catalog.', items: [
        { title: 'Research for product people', body: 'Six weeks. Interviews, synthesis, and the memo your team will read.', meta: 'Cohort' },
        { title: 'Interface writing', body: 'Four weeks. Empty states, errors, and the words in buttons.', meta: 'Cohort' },
      ] },
      { slug: 'instructor', label: 'Instructor', kind: 'about', title: 'Iris Feldman', subtitle: 'I teach the methods I still use on Monday, not a recycled conference talk.' },
      { slug: 'pricing', label: 'Pricing', kind: 'pricing', title: 'Tuition', subtitle: 'Employer invoices welcome. A few need-based seats each cohort.' },
      { slug: 'contact', label: 'Contact', kind: 'contact', title: 'Questions', subtitle: 'Fit, invoices, or whether you should wait for the next round.' },
    ],
    cta: { title: 'Next cohort is the one that fits a working calendar.', subtitle: 'We’ll tell you if you’re better off waiting.', button: 'Apply for a seat' },
    footer: 'Field Notes Academy is fictional education copy for this template.',
  },
  {
    id: 'newsletter',
    name: 'Newsletter & Creator',
    niche: 'Content / Media',
    category: 'education-content',
    description: 'Editorial newsletter site with sample issues, pricing, and subscribe.',
    keywords: ['newsletter', 'substack', 'creator', 'writer', 'blog', 'media'],
    layout: 'editorial',
    theme: {
      mode: 'light',
      primary: '#9f1239',
      accent: '#1c1917',
      background: '#fffbeb',
      surface: '#fff7ed',
      text: '#1c1917',
      muted: '#7c2d12',
      font: 'editorial',
      radius: 'sharp',
    },
    brand: {
      name: 'The Side Table',
      tagline: 'A weekly letter on culture, cities, and the stuff on our desks',
      description: 'Independent writing. Free essays, a paid Sunday edition, and no growth hacks in the footer.',
    },
    hero: {
      eyebrow: 'Weekly · Independent',
      title: 'Essays for people who still read past the fold.',
      subtitle: 'City life, design, and the objects we keep. One letter you can finish on a tram.',
      cta: 'Subscribe free',
      ctaSecondary: 'Read a sample',
    },
    stats: [
      { value: '41k', label: 'Readers' },
      { value: 'Sunday', label: 'Paid edition' },
      { value: '0 ads', label: 'On purpose' },
    ],
    features: [
      { title: 'Free Friday', body: 'A short essay. Always free. Always finishable.' },
      { title: 'Sunday extra', body: 'Longer reported pieces and the recommendations we actually use.' },
      { title: 'Archive', body: 'Searchable. No hostage paywall on year-old work.' },
      { title: 'Events', body: 'A reading in Helsinki twice a year. That’s plenty.' },
    ],
    testimonials: [
      { quote: 'The only newsletter I don’t archive guiltily.', name: 'Reader, since 2022' },
      { quote: 'Writes like a person, not a content engine.', name: 'Another reader' },
    ],
    pricing: [
      { name: 'Free', price: '€0', features: ['Friday letter', 'Archive'] },
      { name: 'Sunday', price: '€7', period: '/mo', features: ['Full archive', 'Sunday extra', 'Annual essay PDF'], highlighted: true },
    ],
    team: [
      { name: 'Isla Quinn', role: 'Writer', bio: 'Former magazine editor. Now sending letters on purpose.' },
    ],
    pages: [
      { slug: 'issues', label: 'Issues', kind: 'list', title: 'Recent letters', subtitle: 'A few free pieces so you know the voice.', items: [
        { title: 'The furniture we keep', body: 'On chairs that outlast the apartment.', meta: 'Friday' },
        { title: 'A tram map of Helsinki bookstores', body: 'Not comprehensive. Just loved.', meta: 'Sunday' },
      ] },
      { slug: 'pricing', label: 'Subscribe', kind: 'pricing', title: 'How to read', subtitle: 'Free is real. Paid is for people who want the longer Sunday.' },
      { slug: 'about', label: 'About', kind: 'about', title: 'Why a letter', subtitle: 'Social feeds expire. A letter can sit on a side table.' },
      { slug: 'contact', label: 'Contact', kind: 'contact', title: 'Write back', subtitle: 'Tips, corrections, and the rare collaboration.' },
    ],
    cta: { title: 'Get Friday’s letter.', subtitle: 'Unsubscribe whenever. We will not send a sequence about it.', button: 'Subscribe' },
    footer: 'The Side Table is fictional newsletter copy for this template.',
  },
  {
    id: 'ecommerce',
    name: 'E-Commerce Store',
    niche: 'Retail / Shopping',
    category: 'ecommerce-events',
    description: 'Product storefront with catalog, detail, cart, and contact.',
    keywords: ['shop', 'store', 'ecommerce', 'retail', 'product', 'buy', 'commerce'],
    layout: 'commerce',
    theme: {
      mode: 'light',
      primary: '#111827',
      accent: '#e11d48',
      background: '#fafafa',
      surface: '#ffffff',
      text: '#111827',
      muted: '#6b7280',
      font: 'sans',
      radius: 'rounded',
    },
    brand: {
      name: 'KOJU',
      tagline: 'Objects for the home that earn their space',
      description: 'A small shop of ceramics, textiles, and tools. Made in Europe, packed in Helsinki.',
    },
    hero: {
      eyebrow: 'New drop · linen',
      title: 'Fewer things. Better ones.',
      subtitle: 'Home goods with honest materials and sizes that fit real apartments. Ships in Finland next day.',
      cta: 'Shop the collection',
      ctaSecondary: 'Our materials',
    },
    stats: [
      { value: 'EU made', label: 'Most goods' },
      { value: '1–2 days', label: 'Finland shipping' },
      { value: '30 days', label: 'Returns' },
    ],
    features: [
      { title: 'Ceramics', body: 'Everyday bowls. Not shrine pieces.' },
      { title: 'Textiles', body: 'Linen that looks better after the third wash.' },
      { title: 'Tools', body: 'Kitchen and desk objects we use in the studio.' },
      { title: 'Gifts', body: 'Wrapped without plastic if you ask at checkout.' },
    ],
    testimonials: [
      { quote: 'The only shop where I didn’t need to return the “one size”.', name: 'Emilia' },
      { quote: 'Packaging was as considered as the bowl.', name: 'Jonas' },
    ],
    pricing: [],
    team: [],
    pages: [
      { slug: 'products', label: 'Shop', kind: 'list', title: 'The collection', subtitle: 'A sample grid. In a live shop this filters and sorts.', items: [
        { title: 'Everyday bowl', body: 'Speckled stoneware. Dishwasher fine.', meta: '€32' },
        { title: 'Washed linen throw', body: '140×200. Gets softer.', meta: '€89' },
        { title: 'Oak cutting board', body: 'Oil it twice a year. That’s the care label.', meta: '€54' },
        { title: 'Brass incense stand', body: 'Small enough for a windowsill.', meta: '€28' },
      ] },
      { slug: 'about', label: 'About', kind: 'about', title: 'A shop with a studio in the back', subtitle: 'KOJU started as a ceramics shelf. The textiles came because we were tired of polyester throws.' },
      { slug: 'cart', label: 'Cart', kind: 'list', title: 'Your cart', subtitle: 'Demo cart — connect a real checkout before launch.', items: [
        { title: 'Cart is a UI in this template', body: 'Replace with your commerce provider when you are ready.' },
      ] },
      { slug: 'contact', label: 'Contact', kind: 'contact', title: 'Questions', subtitle: 'Orders, wholesale, and the occasional missing lid.' },
    ],
    cta: { title: 'Add one thing you will still like in five years.', subtitle: 'Free shipping in Finland over €80.', button: 'Shop now' },
    footer: 'KOJU is a fictional shop for this commerce template.',
  },
  {
    id: 'event-conference',
    name: 'Event & Conference',
    niche: 'Events / Ticketing',
    category: 'ecommerce-events',
    description: 'Conference site with agenda, speakers, tickets, and registration.',
    keywords: ['event', 'conference', 'tickets', 'meetup', 'summit', 'festival'],
    layout: 'event',
    theme: {
      mode: 'dark',
      primary: '#e879f9',
      accent: '#22d3ee',
      background: '#0b0520',
      surface: '#160b33',
      text: '#fdf4ff',
      muted: '#c4b5fd',
      font: 'display',
      radius: 'rounded',
    },
    brand: {
      name: 'SIGNAL 26',
      tagline: 'A two-day conference on making software that lasts',
      description: 'Talks, workshops, and a hall that is not a trade-show maze. Helsinki, November.',
    },
    hero: {
      eyebrow: 'Helsinki · 12–13 Nov',
      title: 'Two days. No booth-babble. Actual talks.',
      subtitle: 'Engineers, designers, and the people who have to ship with them. One track, decent coffee, and a afterparty that ends.',
      cta: 'Get tickets',
      ctaSecondary: 'See the agenda',
    },
    stats: [
      { value: '800', label: 'Capacity' },
      { value: '1 track', label: 'On purpose' },
      { value: '12–13 Nov', label: '2026' },
    ],
    features: [
      { title: 'Talks', body: '30 minutes, then questions. Speakers who have done the work.' },
      { title: 'Workshops', body: 'Wednesday add-on. Laptops out. Ego in the bag.' },
      { title: 'Hall', body: 'One sponsor wall, not a maze. You can find people.' },
      { title: 'Recordings', body: 'For ticket holders. Public a month later.' },
    ],
    testimonials: [
      { quote: 'The first conference where I didn’t need a second track to escape the keynote.', name: 'Attendee ’25' },
      { quote: 'Workshops were actually workshops.', name: 'Staff engineer' },
    ],
    pricing: [
      { name: 'Conference', price: '€349', features: ['Both days', 'Recordings', 'Lunch'] },
      { name: 'Workshop + conf', price: '€549', features: ['Wednesday workshop', 'Everything in Conference'], highlighted: true },
      { name: 'Team of 5', price: '€1,495', features: ['Five conference seats'] },
    ],
    team: [
      { name: 'Kia Nurmi', role: 'Program', bio: 'Curates speakers who can teach, not just perform.' },
      { name: 'Ben Cole', role: 'Producer', bio: 'Venues, catering, and the wifi that actually works.' },
    ],
    pages: [
      { slug: 'agenda', label: 'Agenda', kind: 'list', title: 'The two days', subtitle: 'One track. Titles will lock six weeks out.', items: [
        { title: 'Thu 09:30', body: 'Opening: why most software dies of neglect', meta: 'Keynote' },
        { title: 'Thu 11:00', body: 'Designing tools for experts without scaring everyone else', meta: 'Talk' },
        { title: 'Fri 14:00', body: 'Incidents, memory, and the docs that get read', meta: 'Talk' },
      ] },
      { slug: 'speakers', label: 'Speakers', kind: 'team', title: 'Who’s on stage', subtitle: 'A mix of practitioners. No motivational circuit.' },
      { slug: 'tickets', label: 'Tickets', kind: 'pricing', title: 'Tickets', subtitle: 'Early birds end when they end. We do not fake timers.' },
      { slug: 'register', label: 'Register', kind: 'contact', title: 'Register interest', subtitle: 'We’ll send the real checkout link. This template is the front door.' },
    ],
    cta: { title: 'Save the dates. Bring the people you actually work with.', subtitle: 'Student tickets exist. Email and we’ll not make it a scavenger hunt.', button: 'Get tickets' },
    footer: 'SIGNAL 26 is a fictional conference for this event template.',
  },
  {
    id: 'web3-crypto',
    name: 'Web3 & Crypto',
    niche: 'Blockchain / Web3',
    category: 'emerging-tech',
    description: 'Neon product site with tokenomics, roadmap, and FAQ.',
    keywords: ['web3', 'crypto', 'blockchain', 'token', 'nft', 'defi'],
    layout: 'crypto',
    theme: {
      mode: 'dark',
      primary: '#818cf8',
      accent: '#34d399',
      background: '#020617',
      surface: '#0f172a',
      text: '#e0e7ff',
      muted: '#94a3b8',
      font: 'tech',
      radius: 'rounded',
    },
    brand: {
      name: 'ORBITAL',
      tagline: 'Onchain coordination without the carnival',
      description: 'A protocol and app for treasuries that need votes, payouts, and an audit trail humans can read.',
    },
    hero: {
      eyebrow: 'Mainnet · Q4',
      title: 'Treasury ops that do not require a Discord archaeology degree.',
      subtitle: 'Proposals, payouts, and permissions with a UI your ops lead will use. Open source core. No cartoon mascots.',
      cta: 'Read the docs',
      ctaSecondary: 'See tokenomics',
    },
    stats: [
      { value: '$40M', label: 'Simulated TVL' },
      { value: '12s', label: 'Finality target' },
      { value: 'MIT', label: 'Core license' },
    ],
    features: [
      { title: 'Proposals', body: 'Readable diffs, not 40-page PDFs dropped in a chat.' },
      { title: 'Payouts', body: 'Streaming or one-shot, with a human-readable ledger.' },
      { title: 'Roles', body: 'Who can propose, who can execute. Not everyone is admin.' },
      { title: 'Bridges later', body: 'We ship L2 first. Multi-chain is a roadmap item, not a homepage lie.' },
    ],
    testimonials: [
      { quote: 'Finally a governance UI I can show finance without a translator.', name: 'DAO ops, anonymized' },
      { quote: 'The docs assume intelligence, not airdrop hunger.', name: 'Protocol engineer' },
    ],
    pricing: [],
    team: [
      { name: 'Niko V.', role: 'Protocol', bio: 'Previously infra. Allergic to token theatre.' },
      { name: 'Asha M.', role: 'Product', bio: 'Makes the app usable by people who do not live onchain.' },
    ],
    pages: [
      { slug: 'product', label: 'Product', kind: 'features', title: 'The stack', subtitle: 'App, contracts, and the ledger view finance asked for.' },
      { slug: 'tokenomics', label: 'Tokenomics', kind: 'list', title: 'Token, without the fog machine', subtitle: 'Numbers are placeholders. Replace before any real launch.', items: [
        { title: 'Utility', body: 'Fee discount and proposal bonds. Not a meme.' },
        { title: 'Supply', body: 'Fixed. Emissions only for the security budget.' },
        { title: 'Unlocks', body: 'Team vests. No surprise cliffs in a tweet.' },
      ] },
      { slug: 'roadmap', label: 'Roadmap', kind: 'list', title: 'What’s actually next', subtitle: 'If a date slips, this page should slip with it.', items: [
        { title: 'Now', body: 'Testnet, docs, a boring UI.' },
        { title: 'Next', body: 'Mainnet, audits, payout streams.' },
        { title: 'Later', body: 'More chains if users are already there.' },
      ] },
      { slug: 'faq', label: 'FAQ', kind: 'faq', title: 'Questions we already got', subtitle: 'If your question is “wen moon”, this is the wrong site.' },
      { slug: 'contact', label: 'Contact', kind: 'contact', title: 'Builders & security', subtitle: 'Bug bounty details will live here. Don’t DM seed phrases. Ever.' },
    ],
    cta: { title: 'Read the docs before the timeline.', subtitle: 'Testnet is the product until it isn’t.', button: 'Open the docs' },
    footer: 'ORBITAL is fictional protocol copy for this Web3 template. Not an offer of any token.',
  },
];

export const WEBSITE_TEMPLATES_BY_ID: Record<string, WebsiteTemplate> = Object.fromEntries(
  WEBSITE_TEMPLATES.map((template) => [template.id, template]),
);

export function getWebsiteTemplate(id: string | null | undefined): WebsiteTemplate | null {
  if (!id || id === 'blank') return null;
  return WEBSITE_TEMPLATES_BY_ID[id] ?? null;
}
